### ISSUE TITLE
About the usage of coarse dynamic objects removal

### ISSUE THREAD

**Issue by yuhang9803** [PRBonn/auto-mos#1]
hi, thanks for your excellent work !! there is one problem about this paper
since the REMOVERT, ERASOR methods mainly focus on the map cleaning work of dynamic map , so the output of these methods is usually the detected ghost point cloud(which is the accumulation of dynamic point clouds) in the map instead of the single dynamic point cloud, I am afraid  it may not satisfy the requirement of your training net. 
So how do you handle the ghost point cloud by the above algorithms? In my opinion , maybe you build a static map in advance, and use the static map to identify the dynamic objects when using the single scan??
looking forward to your reply!!

**Comment by Chen-Xieyuanli** [comment]
Hey @yuhang9803, thanks for your interest in our work.

Yes, your are right! We will have the static map in the end. We use the map cleaning method to provide coarse static and non-static parts of the map and then label each point in the scan by checking which part it lies in. More details could be found in Sec.III-B.

I hope it helps!

**Comment by YanhaoWu** [comment]
> Hey @yuhang9803, thanks for your interest in our work.
> 
> Yes, your are right! We will have the static map in the end. We use the map cleaning method to provide coarse static and non-static parts of the map and then label each point in the scan by checking which part it lies in. More details could be found in Sec.III-B.
> 
> I hope it helps!

hello, excellent work!
When will the code of this work be released？

**Comment by Chen-Xieyuanli** [comment]
> 

Hey @WYHbxer, thanks for following our work.

We just realized that one could potentially use our method to automatically generate labels on the test data of our LiDAR-MOS benchmark, which will ruin and kill the benchmark. We therefore may postpone the release of this method.
