### ISSUE TITLE
Only the Tracking Step in this repo?

### ISSUE THREAD

**Issue by zwqnju** [PRBonn/auto-mos#2]
I am very fond of your excellent work. I just run your code according to README. It seems that there is only the tracking step in this repo. 
How can I generate the intermediate instance predictions? Are the other steps (Dynamic Removal, Instance Segmentation, and Network Traning) in your other repos?

Thanks!

**Comment by zwqnju** [comment]
BTW, `pynput` should also be added in the `requirements.txt`

**Comment by Chen-Xieyuanli** [comment]
Hey @zwqnju , thanks for your interest in our work and for your nice feedback.

We just realized that one could potentially use our method to cheat our LiDAR-MOS benchmark. Therefore we postpone the release of the rest part.

We however also provide the links to the original methods used in each module in the readme file ([link](https://github.com/PRBonn/auto-mos#version-10)), and one could use their original codes.
Our method is highly modulized. Other methods that generate instances may also work for our auto-mos.

**Comment by zwqnju** [comment]
Thanks!
